SELECT * 
  FROM (SELECT I.ANIMAL_ID
     , I.NAME
  FROM ANIMAL_INS I
     , ANIMAL_OUTS O
 WHERE 1=1
   AND I.ANIMAL_ID = O.ANIMAL_ID
 ORDER BY O.DATETIME - I.DATETIME DESC)
 WHERE ROWNUM<=2
  
  
  