SELECT EXTRACT (YEAR FROM S.SALES_DATE) YEAR
     , EXTRACT (MONTH FROM S.SALES_DATE) MONTH
     , I.GENDER
     , COUNT(DISTINCT(I.USER_ID)) USERS
  FROM ONLINE_SALE S
     , USER_INFO I
 WHERE S.USER_ID = I.USER_ID(+)
   AND I.GENDER IS NOT NULL
 GROUP BY EXTRACT (YEAR FROM S.SALES_DATE), EXTRACT (MONTH FROM S.SALES_DATE), I.GENDER
 ORDER BY YEAR, MONTH, GENDER
 