SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(O.AMOUNT * P.PRICE) TOTAL_SALES
  FROM FOOD_PRODUCT P
     , FOOD_ORDER O
 WHERE O.PRODUCT_ID = P.PRODUCT_ID
   AND TO_CHAR(O.PRODUCE_DATE, 'YYYYMM') = '202205'
 GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
 ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID;