

SELECT *
  FROM (SELECT A.FLAVOR
          FROM 
             (SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER
                FROM JULY
               GROUP BY FLAVOR) A 
             , FIRST_HALF B
         WHERE A.FLAVOR = B.FLAVOR
         ORDER BY A.TOTAL_ORDER + B.TOTAL_ORDER DESC)
 WHERE ROWNUM <=3